########################
### Sample API documents
########################
sampleapidoc:
  describe:
    member-role:
      fetch: |
        役職情報を取得します。
      regist: |
        役職情報を登録します。下記をリクエストに含めてください。  
        |パラメータ名|概要                                             |
        |----------|------------------------------------------------|
        |`roleName`|役職の名称です。                                   |
        |`weightingValue`|重みづけの値です。0 ~ 9 の範囲で指定してください。|
    price-calculation:
      calc: |
        割り勘価格の計算APIです。入力された役職に紐づく重みづけ値に対して各メンバの割り勘価格を  
        ```
        (メンバの割り勘価格) = メンバの重みづけ値 * (合計額 / 重みづけ値の合計)
        ```
        で計算します。価格については百の位で切り上げを行います。
