########################
### Sample API documents
########################
sampleapidoc:
  describe:
    member-role:
      fetch: |
        役職情報を取得します。
    price-calculation:
      calc: |
        割り勘価格の計算APIです。入力された役職に紐づく重みづけ値に対して各メンバの割り勘価格を  
        ```
        (メンバの割り勘価格) = メンバの重みづけ値 * (合計額 / 重みづけ値の合計)
        ```
        で計算します。価格については百の位で切り上げを行います。
